### ISSUE TITLE
app not working at https://leodog896.github.io/co-authored-by/

### ISSUE THREAD

**Issue by LiNk-NY** [LeoDog896/co-authored-by#3]
Hi Tristan! @LeoDog896 
Thanks for the great app!
I tried to use it recently and it is not working. 
Has the GitHub API changed?

Thanks!

**Comment by LiNk-NY** [comment]
It looks like it is back online. Thanks!

**Comment by tristan-f-r** [comment]
> It looks like it is back online. Thanks!
Forgot to reply to this! Sometimes, my Deno quota shuts down after 2/3rds of the month because of other services I have running. If this becomes a problem again, let me know! :+1:
